/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.qdraw;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.awt.image.ColorModel;
import java.awt.image.WritableRaster;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import java.util.ArrayList;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author JoaoCito
 */
public class LayoutUI extends javax.swing.JFrame {
    static  BufferedImage buffer1 = new BufferedImage( 400, 298, BufferedImage.TYPE_INT_RGB );
    static  BufferedImage buffer2 = new BufferedImage( 400, 298, BufferedImage.TYPE_INT_RGB );
    static  BufferedImage buffer3 = new BufferedImage( 400, 298, BufferedImage.TYPE_INT_RGB );
    static  ArrayList<BufferedImage> desfazer = new ArrayList<BufferedImage>();
    static  ArrayList<BufferedImage> objetos = new ArrayList<BufferedImage>();
    static ArrayList<Integer> forma = new ArrayList<Integer>() ;
    public static boolean flag=true;
    private String n = "";
    static Color cor = Color.BLACK;
    /**
     * Creates new form LayoutUI
     */
    public LayoutUI() {
        initComponents();
       // inicializa();

        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel(criarImagem());
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem11.setText("jMenuItem11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
        );

        jMenu1.setText("Arquivo");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Novo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Abrir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Salvar");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Salvar como ");
        jMenu1.add(jMenuItem4);

        jMenuItem9.setText("Desfazer");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuItem10.setText("Apagar Objeto");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuItem12.setText("Cor");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);
        jMenu1.add(jSeparator1);

        jMenuItem5.setText("Fechar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Inserir");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem6.setText("Retângulo");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Circulo");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Linha");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JFileChooser chooser = new JFileChooser();
        int showDialog = chooser.showDialog(jMenu1, null);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        System.exit(1);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        CriaRetangulo retangulo = new CriaRetangulo();
        retangulo.setVisible(true);
        if(CriaRetangulo.flag)
            jLabel1.setIcon(criaRetangulo(CriaRetangulo.x, CriaRetangulo.y, CriaRetangulo.largura, CriaRetangulo.altura));
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        CriaCirculo circulo = new CriaCirculo();
        circulo.setVisible(true);
        //while(CriaCirculo.flag){}
        if(CriaCirculo.flag)
            jLabel1.setIcon(criaCirculo(CriaCirculo.x, CriaCirculo.y, CriaCirculo.raio, CriaCirculo.raio));
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        CriaLinha linha = new CriaLinha();
        linha.setVisible(true);
        if(CriaLinha.flag)
            jLabel1.setIcon(criaLinha(CriaLinha.x, CriaLinha.y, CriaLinha.xf, CriaLinha.yf));
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        if(desfazer.size()!=1){
        Graphics2D g = buffer2.createGraphics();
        //buffer1 = desfazer.get(desfazer.size()-1);
        g.drawImage(desfazer.get(desfazer.size()-2),0,0, null);
        //JOptionPane.showMessageDialog(null, desfazer.size());
        desfazer.remove(desfazer.size()-1);
        forma.remove(desfazer.size());
        objetos.remove(desfazer.size());
        buffer1 = buffer2;
        //JOptionPane.showMessageDialog(null, desfazer.size());
        jLabel1.setIcon(new ImageIcon (buffer2));// TODO add your handling code here:
        } else {
            desfazer.remove(0);
            jLabel1.setIcon(criarImagem());
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        n = JOptionPane.showInputDialog(null, n);
        //JOptionPane.showMessageDialog(null, Integer.parseInt(n));
        //redesenha(Integer.parseInt(n));// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        cor = JColorChooser.showDialog(jPanel1, "Editando Cor da Figura", cor);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LayoutUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LayoutUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LayoutUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LayoutUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LayoutUI().setVisible(true);
            }
        });
    }
    
    /*private static void inicializa(){
           Graphics g = buffer1.createGraphics();  
        g.setColor( Color.WHITE );  
        g.fillRect( 0, 0, 400, 298); 
        desfazer.add(deepCopy(buffer1));
    }*/
            
    
    private static ImageIcon criarImagem() {  
        //int width=500, height=500;  
          
        Graphics g = buffer1.createGraphics();  
        g.setColor( Color.WHITE );  
        g.fillRect( 0, 0, 400, 298);  
        //g.setColor( cor );  
        //g.drawLine( 0, 0,100, 30 );  
        //g.drawOval(100, 100, 40, 40);
        //g.drawRect(50, 50, 30, 70);
       // buffer2=buffer1;
        //desfazer.add(deepCopy(buffer1));
        return new ImageIcon( buffer1 );  
    }  

     public static ImageIcon criaCirculo(int x, int y, int w,int w1){
        forma.add(1);
        Graphics2D g = buffer2.createGraphics();
        Graphics2D g2= buffer3.createGraphics();
        g.drawImage(buffer1, 0,0 , null);
        //g.setColor( Color.WHITE );
        g.setColor( cor );  
        g.setStroke(new BasicStroke(2.0f));
        //g.fillRect( 0, 0, 300, 200 );  
        g.drawOval(x, y, w, w1);
        g2.setColor( cor );  
        g2.setStroke(new BasicStroke(2.0f)); 
        g2.drawOval(x, y, w, w1);
        objetos.add(deepCopy(buffer3));
        //if(desfazer.size() == 2)
            //desfazer.add(deepCopy(desfazer.get(0)));
        if(flag){
        buffer1=buffer2;
        desfazer.add(deepCopy(buffer1));
        } else{
        desfazer.add(deepCopy(buffer1));
        buffer1=buffer2;}
        
        g.dispose();
        return new ImageIcon(buffer1);
    }
     public static ImageIcon criaRetangulo(int x, int y, int w,int w1){
         forma.add(2);
        Graphics2D g2= buffer3.createGraphics();
        Graphics2D g = buffer2.createGraphics();
        g.drawImage(buffer1, 0,0 , null);
        //g.setColor( Color.WHITE );
        g.setColor( cor );  
        g.setStroke(new BasicStroke(2.0f));
        //g.fillRect( 0, 0, 300, 200 );  
        g.drawRect(x, y, w, w1);
        g2.setColor( cor );  
        g2.setStroke(new BasicStroke(2.0f)); 
        g2.drawRect(x, y, w, w1);
        objetos.add(deepCopy(buffer3));
        if(flag){
        buffer1=buffer2;
        desfazer.add(deepCopy(buffer1));
        } else{
        desfazer.add(deepCopy(buffer1));
        buffer1=buffer2;}
        
        g.dispose();
        return new ImageIcon(buffer1);
    }
    public static ImageIcon criaLinha(int x, int y, int w,int w1){
        forma.add(3);
        Graphics2D g2= buffer3.createGraphics();
        Graphics2D g = buffer2.createGraphics();
        g.drawImage(buffer1, 0,0 , null);
        //g.setColor( Color.WHITE );
        g.setColor( cor );  
        g.setStroke(new BasicStroke(2.0f));
        //g.fillRect( 0, 0, 300, 200 );  
        g.drawLine(x, y, w, w1);
        g2.setColor( cor );  
        g2.setStroke(new BasicStroke(2.0f)); 
        g2.drawLine(x, y, w, w1);
        objetos.add(deepCopy(buffer3));
        if(flag){
        buffer1=buffer2;
        desfazer.add(deepCopy(buffer1));
        } else{
        desfazer.add(deepCopy(buffer1));
        buffer1=buffer2;}
        
        g.dispose();
        return new ImageIcon(buffer1);
    }
    
    
    /*public static void redesenha(int n){
        Graphics2D g = buffer2.createGraphics();
        g.drawImage(objetos.get(0),0,0, null);
        g.setColor( cor );  
        g.setStroke(new BasicStroke(2.0f));
        jLabel1.setIcon(criarImagem());
        objetos.remove(n);
        g.drawImage(objetos.get(0), 0, 0, null);
        for(int i=1;i<objetos.size();i++){
            //if(forma.get(i)==1)
                g.drawImage(objetos.get(i), 0, 0, null);
            //if(forma.get(i)==2)
                
        }
    
    }*/
    static BufferedImage deepCopy(BufferedImage bi) {
        ColorModel cm = bi.getColorModel();
        boolean isAlphaPremultiplied = cm.isAlphaPremultiplied();
        WritableRaster raster = bi.copyData(null);
        return new BufferedImage(cm, raster, isAlphaPremultiplied, null);
    }
    public int getHigh(){
        return this.getHeight();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
   
}
